### ISSUE TITLE
Extend capabilities of needle parameter

### ISSUE THREAD

**Issue by erikengervall** [erikengervall/fast-find-in-files#1]
The `needle` parameter could allow for more than simply a string.

It could be
- RegExp
- Object with advances options for querying

**Comment by EladBezalel** [comment]
I know it's been a while, but this lib is awesome, any chance to get a RegExp support?

**Comment by erikengervall** [comment]
> I know it's been a while, but this lib is awesome, any chance to get a RegExp support?

Oh haven’t looked at this for some time, wasn’t aware there was an interest!

I’ll need to get refamiliarised with the code, can’t promise anything 😅 If you’ve got implementation ideas I’m very open for PRs 🙏🏼

**Comment by EladBezalel** [comment]
Thanks for the quick response :) 

I haven't touched C++ in more than 10 years 😅  but luckily ChatGPT has our back, does this convo gets us anywhere?
https://chat.openai.com/share/c86b3a57-48ff-4a4c-b56b-7e9943c30bf3

**Comment by EladBezalel** [comment]
Hey, i checked it locally and it seems to be working, i think the only problem is multiline regexps, since we're going through the lines and not the entire file, but i guess this is a good starting point.

I also want tot add ignore paths mechanism, but i'll do it in a different pr
